default:
	# nothing

clean:
	@-( cd midiprt ; make fullclean ; cd .. )
	@-( cd schmedit ; make fullclean ; cd .. )
	@-rm -f */*.O */*.o */*.PDB */*.LST */*.ST? */*.BSC */*.bsc */*.ncb */*.opt */*.plg */*.bak
